name: TodoMVC Tests

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.12']
    
    steps:
    - uses: actions/checkout@v4
    
    # Cache Python + pip
    - name: Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
        cache: 'pip'
        
    # Cache Playwright
    - name: üì¶ Cache Playwright
      uses: actions/cache@v4
      with:
        path: ~/.cache/ms-playwright
        key: playwright-${{ hashFiles('**/*.txt') }}
        
    - name: Install deps
      run: |
        pip install -r requirements.txt --only-binary=all  # ‚Üê –¢–æ–ª—å–∫–æ –±–∏–Ω–∞—Ä–Ω–∏–∫–∏!
        playwright install --with-deps chromium
        
    - name: Tests + Reports
      run: |
        mkdir -p reports allure-results
        pytest tests/ -n auto -v
        
    - name: Upload HTML
      uses: actions/upload-artifact@v4
      with:
        name: pytest-html-report
        path: reports/
        
    - name: Upload Allure
      uses: actions/upload-artifact@v4
      with:
        name: allure-results-raw
        path: allure-results/
