name: TodoMVC POM Tests

on:
  push:
  pull_request:
  workflow_dispatch:  # Ручной запуск!

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Python 3.13
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'
        
    - name: Install
      run: |
        pip install -r requirements.txt
        playwright install --with-deps chromium
        
    - name: Tests + Reports
      run: |
        mkdir -p reports
        pytest tests/ -n auto -v
      env:
        PLAYWRIGHT_HEADLESS: "true"
        
    - name: Upload HTML Report
      uses: actions/upload-artifact@v4
      with:
        name: pytest-html-report
        path: reports/
        
    - name: Upload Allure RAW
      uses: actions/upload-artifact@v4
      with:
        name: allure-results-raw
        path: allure-results/
